name: serveo
services:
  serveo:
    build:
      context: /var/www/html/serveo
      dockerfile: Dockerfile
    cpu_shares: 90
    command: []
    container_name: serveo
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    environment:
      - CUSTOM_SUBDOMAIN=
      - LOCAL_HOST=localhost
      - LOCAL_PORT=80
      - REMOTE_PORT=80
      - SSH_OPTIONS=
      - SSH_USER=serveo.net
    hostname: serveo
    image: sakibweb/serveo-docker:latest
    labels:
      icon: https://cdn.prod.website-files.com/570ee6bc69f0b4976a747d2d/5aacf5bec776cc597f8e4126_Frame%202.png
    privileged: true
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports: []
    volumes: []
    devices: []
    cap_add: []
    network_mode: host
x-casaos:
  author: sakibweb
  category: Network
  hostname: ""
  icon: https://cdn.prod.website-files.com/570ee6bc69f0b4976a747d2d/5aacf5bec776cc597f8e4126_Frame%202.png
  index: /
  is_uncontrolled: false
  overview: Serveo provides a simple way to forward localhost ports to the public
    internet via SSH tunneling.
  port_map: ""
  scheme: http
  screenshots:
    - https://cdn.jsdelivr.net/gh/sakibweb/CasaOS-SakibWeb@main/App/Ngrok/screenshot-1.png
  store_app_id: serveo
  tagline:
    custom: Instantly access localhost through Serveo's secure SSH tunneling.
  thumbnail: https://cdn.jsdelivr.net/gh/sakibweb/CasaOS-SakibWeb@main/App/Ngrok/thumbnail.png
  tips:
    custom: |-
      Ensure SSH is configured for autossh tunneling.
      Customize your domain, nginx configuration, and serveo settings as needed.
  title:
    custom: Serveo
